# Generated by Django 4.2.16 on 2024-11-22 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('length', models.IntegerField()),
                ('director', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('starring', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_you_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_rec.movie')),
                ('recom_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='movie_rec.user')),
                ('recom_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='movie_rec.user')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_rec.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_rec.user')),
            ],
        ),
    ]
