# Generated by Django 4.2.16 on 2024-12-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_list',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
