# Generated by Django 4.2.16 on 2024-12-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def disable_foreign_keys(apps, schema_editor):
    schema_editor.execute('PRAGMA foreign_keys=OFF;')  # SQLite
    # For MySQL:
    # schema_editor.execute('SET FOREIGN_KEY_CHECKS=0;')
    # For PostgreSQL:
    # schema_editor.execute('SET CONSTRAINTS ALL DEFERRED;')

def enable_foreign_keys(apps, schema_editor):
    schema_editor.execute('PRAGMA foreign_keys=ON;')  # SQLite
    # For MySQL:
    # schema_editor.execute('SET FOREIGN_KEY_CHECKS=1;')
    # For PostgreSQL:
    # schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE;')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_rec', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(disable_foreign_keys),

        migrations.AddField(
            model_name='user',
            name='adminuser',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
            migrations.AlterField(
            model_name='movie_list',
            name='owner',
            field=models.ForeignKey(to='movie_rec.user', on_delete=models.CASCADE),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recom_from',
            field=models.ForeignKey(to='movie_rec.user', on_delete=models.CASCADE),
        ),

        migrations.RunPython(enable_foreign_keys),
    ]
