# Generated by Django 4.2.16 on 2024-12-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def disable_foreign_keys(apps, schema_editor):
    schema_editor.execute('PRAGMA foreign_keys=OFF;')  # SQLite
    # For MySQL:
    # schema_editor.execute('SET FOREIGN_KEY_CHECKS=0;')
    # For PostgreSQL:
    # schema_editor.execute('SET CONSTRAINTS ALL DEFERRED;')

def enable_foreign_keys(apps, schema_editor):
    schema_editor.execute('PRAGMA foreign_keys=ON;')  # SQLite
    # For MySQL:
    # schema_editor.execute('SET FOREIGN_KEY_CHECKS=1;')
    # For PostgreSQL:
    # schema_editor.execute('SET CONSTRAINTS ALL IMMEDIATE;')

class Migration(migrations.Migration):

    dependencies = [
        ('movie_rec', '0004_user_adminuser'),
    ]

    operations = [
        migrations.RunPython(disable_foreign_keys),

        migrations.AlterField(
            model_name='recommendation',
            name='recom_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='movie_rec.user'),
        ),

        migrations.RunPython(enable_foreign_keys),
    ]
