# Generated by Django 4.2.16 on 2024-10-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='email_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
    ]
